export enum ServerTypes {
  LOBBY = 'LOBBY',
  PROXY = 'PROXY',
  SANDWICH_MASTER = 'SANDWICH_MASTER',
  SANDWICH_SLAVE = 'SANDWICH_SLAVE',
  DISCORD = 'DISCORD',
  MMO = 'MMO',
  BUILD = 'BUILD',
  UNIT_TEST = 'UNIT_TEST',
}
